using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

namespace SRTPluginProviderRE4.Structs.GameStructs
{
    [StructLayout(LayoutKind.Explicit, Pack = 1, Size = 8)]
    public unsafe struct InventoryIDs
    {
        [FieldOffset(0x0)] private int id;
        public int ID => id;
        public string Name => ItemDatabase.ItemNames[ID];
    }

    public class ItemDatabase
    {
        public static Dictionary<int, string> ItemNames = new Dictionary<int, string>()
        {
            { 0, "Magnum Ammo" },
            { 1, "Hand Grenade" },
            { 2, "Incendiary Grenade" },
            { 3, "Matilda" },
            { 4, "Handgun Ammo" },
            { 5, "First Aid Spray" },
            { 6, "Green Herb" },
            { 7, "Rifle Ammo"},
            { 8, "Chicken Egg"},
            { 9, "Brown Chicken Egg"},
            { 10, "Gold Chicken Egg"},
            { 11, "aaa"},
            { 12, "Plaga Sample"},
            { 14, "Flash Grenade"},
            { 15, "Salazar family Insignia"},
            { 16, "Bowgun"},
            { 17, "Bowgun Arrows"},
            { 18, "Green Herb 2x"},
            { 19, "Green Herb 3x"},
            { 20, "Mixed Herb (g+r)"},
            { 21, "Mixed Herb (g+r+y)"},
            { 22, "Mixed Herb (g+y)"},
            { 23, "Rocket Launcher Special"},
            { 24, "Shotgun Ammo"},
            { 25, "Red Herb"},
            { 26, "Handcannon Ammo"},
            { 27, "Hourglass w/ gold decor"},
            { 28, "Yellow Herb"},
            { 29, "Stone Tablet"},
            { 30, "Lion Ornament"},
            { 31, "Goat Ornament"},
            { 32, "TMP Ammo"},
            { 33, "Punisher"},
            { 34, "Punisher with Silencer"},
            { 35, "handgun" },
            { 36, "handgun w/ silencer" },
            { 37, "red9" },
            { 38, "red9 w/ stock" },
            { 39, "blacktail" },
            { 40, "blacktail w/ silencer" },
            { 41, "broken butterfly" },
            { 42, "killer7" },
            { 43, "killer7 w/ silencer" },
            { 44, "shotgun" },
            { 45, "striker" },
            { 46, "rifle" },
            { 47, "rifle (semi-auto)" },
            { 48, "tmp" },
            { 49, "activation key (blue)" },
            { 50, "tmp w/ stock" },
            { 51, "activation key (red)" },
            { 52, "chicago typewriter (infinite)" },
            { 53, "rocket launcher" },
            { 54, "mine thrower" },
            { 55, "handcannon" },
            { 56, "combat knife" },
            { 57, "serpent ornament" },
            { 58, "moonstone (right half)" },
            { 59, "insignia key" },
            { 60, "round insignia" },
            { 61, "false eye" },
            { 62, "custom tmp" },
            { 63, "silencer (handgun)" },
            { 64, "punisher" },
            { 65, "p.r.l. 412" },
            { 66, "stock (red9)" },
            { 67, "stock (tmp)" },
            { 68, "scope (rifle)" },
            { 69, "scope (semi-auto rifle)" },
            { 70, "mine-darts" },
            { 71, "shotgun**" },
            { 72, "capture luis sera" },
            { 73, "target practice" },
            { 74, "luis' memo" },
            { 75, "castellan memo" },
            { 76, "female intruder" },
            { 77, "butler's memo" },
            { 78, "sample retrieved" },
            { 79, "ritual preparation" },
            { 80, "luis' memo 2" },
            { 81, "rifle (semi-auto) w/ infrared scope" },
            { 82, "krauser's bow" },
            { 83, "chicago typewriter (regular)" },
            { 84, "treasure map (castle)" },
            { 85, "treasure map (island)" },
            { 86, "velvet blue" },
            { 87, "spinel" },
            { 88, "pearl pendant" },
            { 89, "brass pocket watch" },
            { 90, "elegant headdress" },
            { 91, "antique pipe" },
            { 92, "gold bangle w/ pearls" },
            { 93, "amber ring" },
            { 94, "beerstein" },
            { 95, "green catseye" },
            { 96, "red catseye" },
            { 97, "yellow catseye" },
            { 98, "beerstein w/ (g)" },
            { 99, "beerstein w/ (r)" },
            { 100, "beerstein w/ (y)" },
            { 101, "beerstein w/ (g,r)" },
            { 102, "beerstein w/ (g,y)" },
            { 103, "beerstein w/ (r,y)" },
            { 104, "beerstein w/ (g,r,y)" },
            { 105, "moonstone (left half)" },
            { 106, "chicago typewriter ammo" },
            { 107, "rifle + scope" },
            { 108, "rifle (semi-auto) w/ scope" },
            { 109, "infinite launcher" },
            { 110, "king's grail" },
            { 111, "queen's grail" },
            { 112, "staff of royalty" },
            { 113, "gold bars" },
            { 114, "arrows" },
            { 115, "bonus time" },
            { 116, "emergency lock card key" },
            { 117, "bonus points" },
            { 118, "green catseye" },
            { 119, "ruby" },
            { 120, "treasure box (s)" },
            { 121, "treasure box (l)" },
            { 122, "blue moonstone" },
            { 123, "key to the mine" },
            { 124, "attache case s" },
            { 125, "attache case m" },
            { 126, "attache case l" },
            { 127, "attache case xl" },
            { 128, "golden sword" },
            { 129, "iron key" },
            { 130, "stone of sacrifice" },
            { 131, "storage room card key" },
            { 132, "freezer card key" },
            { 133, "piece of the holy beast, panther" },
            { 134, "piece of the holy beast, serpent" },
            { 135, "piece of the holy beast, eagle" },
            { 136, "jet-ski key" },
            { 137, "dirty pearl pendant" },
            { 138, "dirty brass pocket watch" },
            { 139, "old key" },
            { 140, "camp key" },
            { 141, "dynamite" },
            { 142, "lift activation key" },
            { 143, "gold bangle" },
            { 144, "elegant perfume bottle" },
            { 145, "mirror w/ pearls & rubies" },
            { 146, "waste disposal card key" },
            { 147, "elegant chessboard" },
            { 148, "riot gun" },
            { 149, "black bass" },
            { 150, "hourglass w/ gold decor" },
            { 151, "black bass (l)" },
            { 152, "illuminados pendant" },
            { 153, "rifle w/ infrared scope" },
            { 154, "crown" },
            { 155, "crown jewel" },
            { 156, "royal insignia" },
            { 157, "crown with jewels" },
            { 158, "crown with an insignia" },
            { 159, "salazar family crown" },
            { 160, "rifle ammo (infrared)" },
            { 161, "emerald" },
            { 162, "bottle caps" },
            { 163, "gallery key" },
            { 164, "emblem (right half)" },
            { 165, "emblem (left half)" },
            { 166, "hexagonal emblem" },
            { 167, "castle gate key" },
            { 168, "mixed herbs (r+y)" },
            { 169, "treasure map (village)" },
            { 170, "scope (mine-thrower)" },
            { 171, "mine-thrower + scope" },
            { 172, "playing manual 1" },
            { 173, "info on ashley" },
            { 174, "playing manual 2" },
            { 175, "alert order" },
            { 176, "about the blue medallions" },
            { 177, "chief's note" },
            { 178, "closure of the church" },
            { 179, "anonymous letter" },
            { 180, "playing manual 3" },
            { 181, "sera and the 3rd party" },
            { 182, "two routes" },
            { 183, "village's last defense" },
            { 184, "butterfly lamp" },
            { 185, "green eye" },
            { 186, "red eye" },
            { 187, "blue eye" },
            { 188, "butterfly lamp w/ ( g )" },
            { 189, "butterfly lamp w/ ( r )" },
            { 190, "butterfly lamp w/ ( b )" },
            { 191, "butterfly lamp w/ ( g, r )" },
            { 192, "butterfly lamp w/ ( g, b )" },
            { 193, "butterfly lamp w/ ( r, b )" },
            { 194, "butterfly lamp w/ ( r, g, b )" },
            { 195, "prison key" },
            { 196, "platinum sword" },
            { 197, "infrared scope" },
            { 198, "elegant mask" },
            { 199, "green gem" },
            { 200, "red gem" },
            { 201, "purple gem" },
            { 202, "elegant mask w/ ( g )" },
            { 203, "elegant mask w/ ( r )" },
            { 204, "elegant mask w/ ( p )" },
            { 205, "elegant mask w/ ( g, r )" },
            { 206, "elegant mask w/ ( g, p )" },
            { 207, "elegant mask w/ ( r, p )" },
            { 208, "elegant mask w/ ( r, g, p )" },
            { 209, "golden lynx" },
            { 210, "green stone of judgement" },
            { 211, "red stone of faith" },
            { 212, "blue stone of treason" },
            { 213, "golden lynx w/ ( g )" },
            { 214, "golden lynx w/ ( r )" },
            { 215, "golden lynx w/ ( b )" },
            { 216, "golden lynx w/ ( g, r )" },
            { 217, "golden lynx w/ ( g, b )" },
            { 218, "golden lynx w/ ( r, b )" },
            { 219, "golden lynx w/ ( g, r, b )" },
            { 220, "leon w/ rocket launcher" },
            { 221, "leon w/ shotgun" },
            { 222, "leon w/ handgun" },
            { 223, "ashley graham" },
            { 224, "luis sera" },
            { 225, "don jose" },
            { 226, "don diego" },
            { 227, "don esteban" },
            { 228, "don manuel" },
            { 229, "dr. salvador" },
            { 230, "merchant" },
            { 231, "zealot w/ scythe" },
            { 232, "zealot w/ shield" },
            { 233, "zealot w/ bowgun" },
            { 234, "leader zealot" },
            { 235, "soldier w/ dynamite" },
            { 236, "soldier w/ stun-rod" },
            { 237, "soldier w/ hammer" },
            { 238, "isabel" },
            { 239, "maria" },
            { 240, "ada wong" },
            { 241, "bella sisters" },
            { 242, "don pedro" },
            { 243, "j.j." },
            { 244, "letter from ada" },
            { 245, "luis' memo 3" },
            { 246, "paper airplane" },
            { 247, "our plan" },
            { 248, "luis' memo 4" },
            { 249, "krauser's note" },
            { 250, "luis' memo 5" },
            { 251, "our mission" },
            { 252, "aaa" },
            { 253, "aaa" },
            { 254, "tactical vest" },
            { 255, "aaa" },
            { 256, "punisher" },
            { 257, "handgun" },
            { 258, "shotgun" },
            { 259, "mine thrower" },
            { 260, "handcannon" },
            { 261, "mine thrower + scope" },
            { 262, "mission directives 1" },
            { 263, "mission directives 2" },
            { 264, "mission directives 3" },
            { 265, "mission directives 4" },
            { 266, "mission directives 5" },
            { 267, "mission 1 treasure map" },
            { 268, "mission 2 treasure map" },
            { 269, "mission 3 treasure map" },
            { 270, "mission 4 treasure map" },
            { 271, "mission 5 treasure map" },
        };
    }
}
